apiVersion: batch.zyc.io/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: kubebuilderproject
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: ubuntu:latest
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

